In [8]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Eiabe\Desktop\vestuario\vendas_loja_nivel1.csv")

In [9]:
df['cliente'] = df['cliente'].fillna("Desconhecido")
df = df.dropna(subset=['quantidade'])

In [10]:
df['quantidade'] = df['quantidade'].astype(int)
df['data_venda'] = pd.to_datetime(df['data_venda'])

In [11]:
duplicadas = ['produto', 'categoria', 'cliente', 'quantidade', 'preco_unitario', 'data_venda']
df = df[duplicadas].drop_duplicates()

In [12]:
padronizacao = ['produto', 'categoria', 'cliente']

for i in padronizacao:
    df[i] = df[i].str.strip()
    df[i] = df[i].str.title()

In [13]:
df['valor_venda'] = df['quantidade'] * df['preco_unitario']

faturamento_total = (df['quantidade'] * df['preco_unitario']).sum()
ranking_quantidade = df.groupby('produto')['quantidade'].sum().reset_index()
ranking_categoria = df.groupby('categoria')['valor_venda'].sum().reset_index()

In [14]:
ranking_quantidade = ranking_quantidade.rename(columns={'quantidade': 'total_vendido'})

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 15 entries, 0 to 18
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   produto         15 non-null     str
 1   categoria       15 non-null     str
 2   cliente         15 non-null     str
 3   quantidade      15 non-null     int64
 4   preco_unitario  15 non-null     float64
 5   data_venda      15 non-null     datetime64[us]
 6   valor_venda     15 non-null     float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 960.0 bytes

In [16]:
df.head()

,produto,categoria,cliente,quantidade,preco_unitario,data_venda,valor_venda
0,Caderno,Papelaria,Ana Souza,10,15.0,2024-01-05,150.0
1,Caneta Azul,Papelaria,Bruno Lima,50,3.5,2024-01-05,175.0
3,Caneta Preta,Papelaria,Ana Souza,30,3.5,2024-01-06,105.0
4,Fone De Ouvido,Eletronicos,Desconhecido,8,89.9,2024-01-07,719.2
5,Estojo,Acessorios,Diego Alves,15,22.0,2024-01-07,330.0

In [17]:
ranking_quantidade['total_vendido'] = ranking_quantidade['total_vendido'].astype(int)

ranking_quantidade = ranking_quantidade.sort_values(by='total_vendido', ascending = False)

ranking_quantidade

          produto  total_vendido
1     Caneta Azul             90
2    Caneta Preta             65
0         Caderno             53
6           Mouse             32
3          Estojo             15
4  Fone De Ouvido             14
7         Teclado              9
5         Mochila              8

In [18]:
ranking_categoria['ranking'] = ranking_categoria['valor_venda'].rank(ascending=False, method= 'min')
ranking_categoria['ranking'] = ranking_categoria['ranking'].astype(int)
ranking_categoria = ranking_categoria.sort_values(by='ranking')


ranking_categoria

     categoria  valor_venda  ranking
1  Eletronicos       3553.6        1
2    Papelaria       1337.5        2
0   Acessorios       1290.0        3

In [19]:
faturamento_total

np.float64(6181.1)